services:
    app:
        build:
            context: ./docker/php
            args:
                UID: ${UID}
                GID: ${GID}
        container_name: app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
            - "5173:5173"
        depends_on:
            - db
        user: "${UID}:${GID}"

    db:
        image: postgres:15
        container_name: db
        restart: unless-stopped
        environment:
            POSTGRES_USER: rootroot
            POSTGRES_PASSWORD: supersecretdecksanddicespassword
            POSTGRES_DB: decks_and_dices
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data:
